pipeline {
    agent any

    tools {
        maven "M3"
    }

    environment {
        IMAGE_NAME = "alxhxc/spock-lizard-docker"
        IMAGE_TAG = "latest"
        GIT_REPO = 'https://github.com/cameronmcnz/spock-lizard-docker.git'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Clone Repository') {
            steps {
                git "${GIT_REPO}"
            }
        }

        stage('Compile and Test') {
            steps {
                sh "mvn clean compile test"
            }
        }


        stage('Build Spring Boot JAR File') {
            steps {
                sh "mvn clean package spring-boot:repackage"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // With Docker Plugin
                    /* dockerImage = docker.build("${IMAGE_NAME}:${IMAGE_TAG}") */

                    // Without Docker Plugin
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // With Docker Plugin
                    /* docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        dockerImage.push() */

                    // Without Docker Plugin
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "echo Pushing Docker Image to Docker Hub..."
                        sh "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
                        sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                    }
                }
            }
        }
    }
}