pipeline {
    agent any

    tools {
        maven "M3"
    }

    environment {
        GIT_REPO = 'https://github.com/alxhxc/spock-lizard-docker.git'
        DOCKERHUB_AUTH_TOKEN = credentials('dockerhub-token')
    }

    parameters { 
        
        choice(
            name: 'USER',
            choices: ['alxhxc', 'alex.hlt-doNotUse', 'chikibby'],
            description: 'Select the Docker Repository user'
        )

        string(
            name: 'VERSION',
            defaultValue: 'latest',
            description: 'Version of the Docker image'
        )
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Clone Repository') {
            steps {
                git "${GIT_REPO}"
            }
        }

        stage('Compile and Test') {
            steps {
                sh "mvn clean compile test"
            }
        }


        stage('Build Spring Boot JAR File') {
            steps {
                sh "mvn clean package spring-boot:repackage"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // With Docker Plugin
                    /* dockerImage = docker.build("${IMAGE_NAME}:${IMAGE_TAG}") */

                    // Without Docker Plugin
                    sh "docker build -t ${params.USER}/spock-lizard-docker:${params.VERSION} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // With Docker Plugin
                    /* docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        dockerImage.push() */

                    // Without Docker Plugin
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "echo Pushing Docker Image to Docker Hub..."
                        sh "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
                        sh "docker push ${params.USER}/spock-lizard-docker:${params.VERSION}"
                    }
                }
            }

        // Using a different approach to push the Docker image using a docker hub t
/*         stage('Push Docker Image') {
            steps {
            script {
                sh "echo Pushing Docker Image to Docker Hub..."
                sh "echo ${DOCKERHUB_AUTH_TOKEN} | docker login -u ${params.USER} --password-stdin"
                sh "docker push ${params.USER}/spock-lizard-docker:${params.VERSION}"
            }
            }
        } */
}
    }

    post {
        always {
            cleanWs()
        }
    }
}
